### ISSUE TITLE
Remove unused font subset

### ISSUE THREAD

**Issue by Nischal2015** [Yunika-Bajracharya/Yunika-Bajracharya.github.io#1]
Consider using only the subsets of the font that are actually being used in the site. This can be done by including `subsets` parameters while importing the Google Fonts.

If `subsets` don't seem to work, you can use `@font-face`directive as used by Google Fonts under the hood. 

Even better you can self-host the fonts.

Refer to `web.dev` or google developer site for details.

Using only subset of fonts significantly helps improve `FCP`, `LCP` and `speed index` metrics.
You can find these metrics under the `Performance` section of `Lighthouse`

**Comment by Yunika-Bajracharya** [comment]
Sure, will work on it. Thanks!
